---
title: "Conference posters"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

* **Macuch Silva, V**, Franke, M., & Degen, J. (2018, June). _Reading quantified expressions in context: Does pragmatic surprisal or strategic attention allocation predict self-paced reading times?_ Poster presented at the XPrag.de Annual Meeting, Graz.

* Franke, M., Degen, J., & **Macuch Silva, V**. (2017, September). _Probabilistic modeling of pragmatic processing and utterance production_. Poster presented at the XPrag.de Annual Meeting, Cologne.

* **Macuch Silva, V.**, & Roberts, S. (2016, April). Language Adapts To Signal Disruption In Interaction. In S.G. Roberts, C. Cuskley, L. McCrohon, L. Barceló-Coblijn, O. Feher & T. Verhoef, _The Evolution of Language: Proceedings of the 11th International Conference (EVOLANG11)_. 

* **Macuch Silva, V.**, & Roberts, S. (2015, June). _Does repair affect the emergence of structure in language?_ Poster presented at TABU Dag, Groningen.