---
title: "Presentations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

**Peer-reviewed talks**

* **Macuch Silva, V.**, & Jamieson, E (2021, February). _Processing polar questions in context with varying epistemic biases in English_. Biased Questions: Experimental Results & Theoretical Modelling, Berlin. [<a href="Processing-polar-questions-in-contexts-with-varying-epistemic-biases-in-English.pdf" target="_blank"><b>abstract</b></a>]

* Roberts, F., **Macuch Silva, V.**, & Rohde, H. (2020, July [postponed to July 2021]). _Non-actual 'actual': Expectations for upcoming figurative language arise from cues about message truth_. 5th Usage-Based Linguistics Conference, Tel Aviv. [<a href="UBL-submission.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch Silva, V.**, Roberts, F., & Rohde, H. (2020, June [postponed to January 2021]). _Do truth-endorsing adjectives act as cues to non-literality in the processing of modified metaphors? A psycholinguistic investigation of English 'actual', 'literal', and 'real'_. TExMod2020: Theoretical and
Experimental Approaches to Modification, Tübingen. [<a href="TruthEndorsingAdjectives.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch Silva, V.**, & Franke, M. (2018, June). _Reading quantified expressions in context: Does pragmatic surprisal or strategic attention allocation predict self-paced reading times?_ The pragmatics of quantifiers: implicature and presupposition – experiment and theory, Berlin.

* **Macuch Silva, V.**, Holler, J., Özyürek, A., & Roberts, S. G. (2018). Modality-specific effects on language emergence - and why looking at interaction also matters. In H. Little & A. Micklos (Eds.), _The proceedings of the evolang xii modality matters workshop_, 16 April, 2018. [<a href="https://hlittle.com/MM/allpaperpdfs/EvoLangMM_paper3.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch Silva, V.**, Roberts, S., Holler, J., & Özyürek, A. (2017, September). _An experimental study of multimodal communication and early language emergence_. Protolang 5, Barcelona. [<a href="http://cbl.ub.edu/wp-content/uploads/2017/09/protolang5_book_of_abstracts.pdf#page=32" target="_blank"><b>abstract</b></a>]

* **Macuch Silva, V.**, & Roberts, S. (2016) Exploring the Role of Interaction in the Emergence of Linguistic Structure. In S. Roberts & G. Mills (Eds.) _Proceedings of EvoLang XI, Language Adapts to Interaction Workshop_, 21 March, 2016. [<a href="https://evolang.org/neworleans/workshops/pdf/MacuchSilva_Lati.pdf" target="_blank"><b>abstract</b></a>]


**Conference posters**

* **Macuch Silva, V.**, Cummins, C., & Franke, M. (2020, July). _Modeling manipulative language use_. Poster presented at CogSci 2020 Virtual Conference. [<a href="https://cognitivesciencesociety.org/cogsci20/papers/0382/0382.pdf" target="_blank"><b>abstract</b></a>] [<a href="Poster-CogSci2020.pdf" target="_blank"><b>poster</b></a>] [<a href="Poster-video-CogSci2020.mp4" target="_blank"><b>summary video</b></a>]

* **Macuch Silva, V.**, & Franke, M. (2019, November). _Do the German discourse particles eigentlich and tatsächlich modulate online expectations about intended meaning?_ Poster presented at the XPrag.de Annual Meeting, Berlin. [<a href="Poster-XPrag2019.pdf" target="_blank"><b>poster</b></a>]

* **Macuch Silva, V.**, Franke, M., & Degen, J. (2018, June). _Reading quantified expressions in context: Does pragmatic surprisal or strategic attention allocation predict self-paced reading times?_ Poster presented at the XPrag.de Annual Meeting, Graz. [<a href="Poster-XPrag2018.pdf" target="_blank"><b>poster</b></a>]

* Franke, M., Degen, J., & **Macuch Silva, V**. (2017, September). _Probabilistic modeling of pragmatic processing and utterance production_. Poster presented at the XPrag.de Annual Meeting, Cologne. [<a href="Poster-XPrag2017.pdf" target="_blank"><b>poster</b></a>]

* **Macuch Silva, V.**, & Roberts, S. (2016, April). Language Adapts To Signal Disruption In Interaction. In S.G. Roberts, C. Cuskley, L. McCrohon, L. Barceló-Coblijn, O. Feher & T. Verhoef, _The Evolution of Language: Proceedings of the 11th International Conference (EVOLANG11)_. [<a href="https://evolang.org/neworleans/pdf/EVOLANG_11_paper_20.pdf" target="_blank"><b>abstract</b></a>]

* **Macuch Silva, V.**, & Roberts, S. (2015, June). _Does repair affect the emergence of structure in language?_ Poster presented at TABU Dag, Groningen. [<a href="Poster-TABU-Dag.pdf" target="_blank"><b>poster</b></a>]