---
title: "Publications"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
body {
  text-align: justify}

h1 {
  text-align: center
}
</style>

**Journal papers**

* **Macuch Silva, V.**,  Holler, J., Özyürek, A., & Roberts, S. (2019). _Multimodality and the origin of a novel communication system in face-to-face interaction._ Manuscript submitted for publication. [[**online repository**]](https://github.com/seannyD/multimodalCommunicationGame)


**Conference papers**

* Micklos, A., **Macuch Silva, V.**, & Fay, N. (2018). The prevalence of repair in studies of language evolution. In Cuskley, C., Flaherty, M., Little, H., McCrohon, L., Ravignani, A. & Verhoef, T. (Eds.): _The Evolution of Language: Proceedings of the 12th International Conference (EVOLANGXII)_. [[**abstract**](http://evolang.org/torun/proceedings/paperpdfs/Evolang_12_paper_136.pdf)]


* **Macuch Silva, V.**, & Roberts. S. (2016). Language Adapts To Signal Disruption In Interaction. In S.G. Roberts, C. Cuskley, L. McCrohon, L. Barceló-Coblijn, O. Feher & T. Verhoef, _The Evolution of Language: Proceedings of the 11th International Conference (EVOLANG11)_. [[**abstract**](http://evolang.org/neworleans/workshops/pdf/MacuchSilva_Lati.pdf)]